package mcv.tictactoe;
import com.mrjaffesclass.apcs.messenger.*;
import javax.swing.JButton;
/**
 * MVC Template
 * This is a template of an MVC framework used by APCS for the 
 * LandMine project (and others)
 * @author Roger Jaffe
 * @version 1.0
 * 
 */
public class View extends javax.swing.JFrame implements MessageHandler {

  private final Messenger mvcMessaging;
  
  /**
   * Creates a new view
   * @param messages mvcMessaging object
   */
  public View(Messenger messages) {
    mvcMessaging = messages;   // Save the calling controller instance
    initComponents();           // Create and init the GUI components
  }
  
  /**
   * Initialize the model here and subscribe
   * to any required messages
   */
  public void init() {
    // Subscribe to messages here
    mvcMessaging.subscribe("model:variable1Changed", this);
    mvcMessaging.subscribe("model:variable2Changed", this);
    this.mvcMessaging.subscribe("boardChange", this);
    this.mvcMessaging.subscribe("gameOver", this);
  }
  
  @Override
  public void messageHandler(String messageName, Object messagePayload) {
    if (messagePayload != null) {
      System.out.println("MSG: received by view: "+messageName+" | "+messagePayload.toString());
    } else {
      System.out.println("MSG: received by view: "+messageName+" | No data sent");
    }
    if (messageName.equals("boardChange")) {
      // Get the message payload and cast it as a 2D string array since we
      // know that the model is sending out the board data with the message
      String[][] board = (String[][])messagePayload;
      // Now set the button text with the contents of the board
      a1.setText(board[0][0]);
      a00.setText(board[0][1]);
      a3.setText(board[0][2]);
      a9.setText(board[1][0]);
      a8.setText(board[1][1]);
      a11.setText(board[1][2]);
      a18.setText(board[2][0]);
      a20.setText(board[2][1]);
      a19.setText(board[2][2]);
      a5.setText(board[0][3]);
      a4.setText(board[0][4]);
      a6.setText(board[0][5]);
      a7.setText(board[0][6]);
      a2.setText(board[0][7]);
      a13.setText(board[1][3]);
      a12.setText(board[1][4]);
      a14.setText(board[1][5]);
      a15.setText(board[1][6]);
      a10.setText(board[1][7]);
      a16.setText(board[2][3]);
      a22.setText(board[2][4]);
      a21.setText(board[2][5]);
      a17.setText(board[2][6]);
      a23.setText(board[2][7]);
      a25.setText(board[3][0]);
      a28.setText(board[3][1]);
      a26.setText(board[3][2]);
      a27.setText(board[3][3]);
      a30.setText(board[3][4]);
      a29.setText(board[3][5]);
      a31.setText(board[3][6]);
      a24.setText(board[3][7]);
      a37.setText(board[4][0]);
      a34.setText(board[4][1]);
      a35.setText(board[4][2]);
      a39.setText(board[4][3]);
      a38.setText(board[4][4]);
      a32.setText(board[4][5]);
      a33.setText(board[4][6]);
      a36.setText(board[4][7]);
      a43.setText(board[5][0]);
      a44.setText(board[5][1]);
      a42.setText(board[5][2]);
      a41.setText(board[5][3]);
      a47.setText(board[5][4]);
      a46.setText(board[5][5]);
      a45.setText(board[5][6]);
      a40.setText(board[5][7]);
      a63.setText(board[6][0]);
      a60.setText(board[6][1]);
      a61.setText(board[6][2]);
      a49.setText(board[6][3]);
      a48.setText(board[6][4]);
      a58.setText(board[6][5]);
      a59.setText(board[6][6]);
      a62.setText(board[6][7]);
      a53.setText(board[7][0]);
      a54.setText(board[7][1]);
      a52.setText(board[7][2]);
      a51.setText(board[7][3]);
      a57.setText(board[7][4]);
      a56.setText(board[7][5]);
      a55.setText(board[7][6]);
      a50.setText(board[7][7]);
      jLabel1.setText("Red has " + checkRed(messagePayload));
      jLabel2.setText("Blue has" + checkBlue(messagePayload));
      if (checkRed(messagePayload)+ checkBlue(messagePayload) == 64) {
          if (checkRed(messagePayload) > checkBlue(messagePayload)) {
              jLabel3.setText("Red Is The Winner");
          } else if (checkRed(messagePayload) < checkBlue(messagePayload)) {
              jLabel3.setText("Blue Is The Winner");
          } else {
              jLabel3.setText("It is a Tie");
          }
      }
    }
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a00 = new javax.swing.JButton();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        a6 = new javax.swing.JButton();
        a7 = new javax.swing.JButton();
        a8 = new javax.swing.JButton();
        a9 = new javax.swing.JButton();
        a10 = new javax.swing.JButton();
        a11 = new javax.swing.JButton();
        a12 = new javax.swing.JButton();
        a13 = new javax.swing.JButton();
        a14 = new javax.swing.JButton();
        a15 = new javax.swing.JButton();
        a16 = new javax.swing.JButton();
        a17 = new javax.swing.JButton();
        a18 = new javax.swing.JButton();
        a19 = new javax.swing.JButton();
        a20 = new javax.swing.JButton();
        a21 = new javax.swing.JButton();
        a22 = new javax.swing.JButton();
        a23 = new javax.swing.JButton();
        a24 = new javax.swing.JButton();
        a25 = new javax.swing.JButton();
        a26 = new javax.swing.JButton();
        a27 = new javax.swing.JButton();
        a28 = new javax.swing.JButton();
        a29 = new javax.swing.JButton();
        a30 = new javax.swing.JButton();
        a31 = new javax.swing.JButton();
        a32 = new javax.swing.JButton();
        a33 = new javax.swing.JButton();
        a34 = new javax.swing.JButton();
        a35 = new javax.swing.JButton();
        a36 = new javax.swing.JButton();
        a37 = new javax.swing.JButton();
        a38 = new javax.swing.JButton();
        a39 = new javax.swing.JButton();
        a40 = new javax.swing.JButton();
        a41 = new javax.swing.JButton();
        a42 = new javax.swing.JButton();
        a43 = new javax.swing.JButton();
        a44 = new javax.swing.JButton();
        a45 = new javax.swing.JButton();
        a46 = new javax.swing.JButton();
        a47 = new javax.swing.JButton();
        a48 = new javax.swing.JButton();
        a49 = new javax.swing.JButton();
        a50 = new javax.swing.JButton();
        a51 = new javax.swing.JButton();
        a52 = new javax.swing.JButton();
        a53 = new javax.swing.JButton();
        a54 = new javax.swing.JButton();
        a55 = new javax.swing.JButton();
        a56 = new javax.swing.JButton();
        a57 = new javax.swing.JButton();
        a58 = new javax.swing.JButton();
        a59 = new javax.swing.JButton();
        a60 = new javax.swing.JButton();
        a61 = new javax.swing.JButton();
        a62 = new javax.swing.JButton();
        a63 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N

        a00.setMaximumSize(new java.awt.Dimension(75, 75));
        a00.setMinimumSize(new java.awt.Dimension(75, 75));
        a00.setPreferredSize(new java.awt.Dimension(75, 75));
        a00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a1.setMaximumSize(new java.awt.Dimension(75, 75));
        a1.setMinimumSize(new java.awt.Dimension(75, 75));
        a1.setPreferredSize(new java.awt.Dimension(75, 75));
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a2.setMaximumSize(new java.awt.Dimension(75, 75));
        a2.setMinimumSize(new java.awt.Dimension(75, 75));
        a2.setName(""); // NOI18N
        a2.setPreferredSize(new java.awt.Dimension(75, 75));
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a3.setMaximumSize(new java.awt.Dimension(75, 75));
        a3.setMinimumSize(new java.awt.Dimension(75, 75));
        a3.setName(""); // NOI18N
        a3.setPreferredSize(new java.awt.Dimension(75, 75));
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a4.setMaximumSize(new java.awt.Dimension(75, 75));
        a4.setMinimumSize(new java.awt.Dimension(75, 75));
        a4.setName(""); // NOI18N
        a4.setPreferredSize(new java.awt.Dimension(75, 75));
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a5.setMaximumSize(new java.awt.Dimension(75, 75));
        a5.setMinimumSize(new java.awt.Dimension(75, 75));
        a5.setName(""); // NOI18N
        a5.setPreferredSize(new java.awt.Dimension(75, 75));
        a5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a6.setMaximumSize(new java.awt.Dimension(75, 75));
        a6.setMinimumSize(new java.awt.Dimension(75, 75));
        a6.setName(""); // NOI18N
        a6.setPreferredSize(new java.awt.Dimension(75, 75));
        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a7.setMaximumSize(new java.awt.Dimension(75, 75));
        a7.setMinimumSize(new java.awt.Dimension(75, 75));
        a7.setName(""); // NOI18N
        a7.setPreferredSize(new java.awt.Dimension(75, 75));
        a7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a8.setMaximumSize(new java.awt.Dimension(75, 75));
        a8.setMinimumSize(new java.awt.Dimension(75, 75));
        a8.setPreferredSize(new java.awt.Dimension(75, 75));
        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a9.setMaximumSize(new java.awt.Dimension(75, 75));
        a9.setMinimumSize(new java.awt.Dimension(75, 75));
        a9.setPreferredSize(new java.awt.Dimension(75, 75));
        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a10.setMaximumSize(new java.awt.Dimension(75, 75));
        a10.setMinimumSize(new java.awt.Dimension(75, 75));
        a10.setName(""); // NOI18N
        a10.setPreferredSize(new java.awt.Dimension(75, 75));
        a10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a11.setMaximumSize(new java.awt.Dimension(75, 75));
        a11.setMinimumSize(new java.awt.Dimension(75, 75));
        a11.setName(""); // NOI18N
        a11.setPreferredSize(new java.awt.Dimension(75, 75));
        a11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a12.setMaximumSize(new java.awt.Dimension(75, 75));
        a12.setMinimumSize(new java.awt.Dimension(75, 75));
        a12.setName(""); // NOI18N
        a12.setPreferredSize(new java.awt.Dimension(75, 75));
        a12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a13.setMaximumSize(new java.awt.Dimension(75, 75));
        a13.setMinimumSize(new java.awt.Dimension(75, 75));
        a13.setName(""); // NOI18N
        a13.setPreferredSize(new java.awt.Dimension(75, 75));
        a13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a14.setMaximumSize(new java.awt.Dimension(75, 75));
        a14.setMinimumSize(new java.awt.Dimension(75, 75));
        a14.setName(""); // NOI18N
        a14.setPreferredSize(new java.awt.Dimension(75, 75));
        a14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a15.setMaximumSize(new java.awt.Dimension(75, 75));
        a15.setMinimumSize(new java.awt.Dimension(75, 75));
        a15.setName(""); // NOI18N
        a15.setPreferredSize(new java.awt.Dimension(75, 75));
        a15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a16.setMaximumSize(new java.awt.Dimension(75, 75));
        a16.setMinimumSize(new java.awt.Dimension(75, 75));
        a16.setName(""); // NOI18N
        a16.setPreferredSize(new java.awt.Dimension(75, 75));
        a16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a17.setMaximumSize(new java.awt.Dimension(75, 75));
        a17.setMinimumSize(new java.awt.Dimension(75, 75));
        a17.setName(""); // NOI18N
        a17.setPreferredSize(new java.awt.Dimension(75, 75));
        a17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a18.setMaximumSize(new java.awt.Dimension(75, 75));
        a18.setMinimumSize(new java.awt.Dimension(75, 75));
        a18.setPreferredSize(new java.awt.Dimension(75, 75));
        a18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a19.setMaximumSize(new java.awt.Dimension(75, 75));
        a19.setMinimumSize(new java.awt.Dimension(75, 75));
        a19.setName(""); // NOI18N
        a19.setPreferredSize(new java.awt.Dimension(75, 75));
        a19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a20.setMaximumSize(new java.awt.Dimension(75, 75));
        a20.setMinimumSize(new java.awt.Dimension(75, 75));
        a20.setPreferredSize(new java.awt.Dimension(75, 75));
        a20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a21.setMaximumSize(new java.awt.Dimension(75, 75));
        a21.setMinimumSize(new java.awt.Dimension(75, 75));
        a21.setName(""); // NOI18N
        a21.setPreferredSize(new java.awt.Dimension(75, 75));
        a21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a22.setMaximumSize(new java.awt.Dimension(75, 75));
        a22.setMinimumSize(new java.awt.Dimension(75, 75));
        a22.setName(""); // NOI18N
        a22.setPreferredSize(new java.awt.Dimension(75, 75));
        a22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a23.setMaximumSize(new java.awt.Dimension(75, 75));
        a23.setMinimumSize(new java.awt.Dimension(75, 75));
        a23.setName(""); // NOI18N
        a23.setPreferredSize(new java.awt.Dimension(75, 75));
        a23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a24.setMaximumSize(new java.awt.Dimension(75, 75));
        a24.setMinimumSize(new java.awt.Dimension(75, 75));
        a24.setName(""); // NOI18N
        a24.setPreferredSize(new java.awt.Dimension(75, 75));
        a24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a25.setMaximumSize(new java.awt.Dimension(75, 75));
        a25.setMinimumSize(new java.awt.Dimension(75, 75));
        a25.setPreferredSize(new java.awt.Dimension(75, 75));
        a25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a26.setMaximumSize(new java.awt.Dimension(75, 75));
        a26.setMinimumSize(new java.awt.Dimension(75, 75));
        a26.setName(""); // NOI18N
        a26.setPreferredSize(new java.awt.Dimension(75, 75));
        a26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a27.setMaximumSize(new java.awt.Dimension(75, 75));
        a27.setMinimumSize(new java.awt.Dimension(75, 75));
        a27.setName(""); // NOI18N
        a27.setPreferredSize(new java.awt.Dimension(75, 75));
        a27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a28.setMaximumSize(new java.awt.Dimension(75, 75));
        a28.setMinimumSize(new java.awt.Dimension(75, 75));
        a28.setPreferredSize(new java.awt.Dimension(75, 75));
        a28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a29.setMaximumSize(new java.awt.Dimension(75, 75));
        a29.setMinimumSize(new java.awt.Dimension(75, 75));
        a29.setName(""); // NOI18N
        a29.setPreferredSize(new java.awt.Dimension(75, 75));
        a29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a30.setMaximumSize(new java.awt.Dimension(75, 75));
        a30.setMinimumSize(new java.awt.Dimension(75, 75));
        a30.setName(""); // NOI18N
        a30.setPreferredSize(new java.awt.Dimension(75, 75));
        a30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a31.setMaximumSize(new java.awt.Dimension(75, 75));
        a31.setMinimumSize(new java.awt.Dimension(75, 75));
        a31.setName(""); // NOI18N
        a31.setPreferredSize(new java.awt.Dimension(75, 75));
        a31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a32.setMaximumSize(new java.awt.Dimension(75, 75));
        a32.setMinimumSize(new java.awt.Dimension(75, 75));
        a32.setName(""); // NOI18N
        a32.setPreferredSize(new java.awt.Dimension(75, 75));
        a32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a33.setMaximumSize(new java.awt.Dimension(75, 75));
        a33.setMinimumSize(new java.awt.Dimension(75, 75));
        a33.setName(""); // NOI18N
        a33.setPreferredSize(new java.awt.Dimension(75, 75));
        a33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a34.setMaximumSize(new java.awt.Dimension(75, 75));
        a34.setMinimumSize(new java.awt.Dimension(75, 75));
        a34.setPreferredSize(new java.awt.Dimension(75, 75));
        a34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a35.setMaximumSize(new java.awt.Dimension(75, 75));
        a35.setMinimumSize(new java.awt.Dimension(75, 75));
        a35.setName(""); // NOI18N
        a35.setPreferredSize(new java.awt.Dimension(75, 75));
        a35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a36.setMaximumSize(new java.awt.Dimension(75, 75));
        a36.setMinimumSize(new java.awt.Dimension(75, 75));
        a36.setName(""); // NOI18N
        a36.setPreferredSize(new java.awt.Dimension(75, 75));
        a36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a37.setMaximumSize(new java.awt.Dimension(75, 75));
        a37.setMinimumSize(new java.awt.Dimension(75, 75));
        a37.setPreferredSize(new java.awt.Dimension(75, 75));
        a37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a38.setMaximumSize(new java.awt.Dimension(75, 75));
        a38.setMinimumSize(new java.awt.Dimension(75, 75));
        a38.setName(""); // NOI18N
        a38.setPreferredSize(new java.awt.Dimension(75, 75));
        a38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a39.setMaximumSize(new java.awt.Dimension(75, 75));
        a39.setMinimumSize(new java.awt.Dimension(75, 75));
        a39.setName(""); // NOI18N
        a39.setPreferredSize(new java.awt.Dimension(75, 75));
        a39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a40.setMaximumSize(new java.awt.Dimension(75, 75));
        a40.setMinimumSize(new java.awt.Dimension(75, 75));
        a40.setName(""); // NOI18N
        a40.setPreferredSize(new java.awt.Dimension(75, 75));
        a40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a41.setMaximumSize(new java.awt.Dimension(75, 75));
        a41.setMinimumSize(new java.awt.Dimension(75, 75));
        a41.setName(""); // NOI18N
        a41.setPreferredSize(new java.awt.Dimension(75, 75));
        a41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a42.setMaximumSize(new java.awt.Dimension(75, 75));
        a42.setMinimumSize(new java.awt.Dimension(75, 75));
        a42.setName(""); // NOI18N
        a42.setPreferredSize(new java.awt.Dimension(75, 75));
        a42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a43.setMaximumSize(new java.awt.Dimension(75, 75));
        a43.setMinimumSize(new java.awt.Dimension(75, 75));
        a43.setPreferredSize(new java.awt.Dimension(75, 75));
        a43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a44.setMaximumSize(new java.awt.Dimension(75, 75));
        a44.setMinimumSize(new java.awt.Dimension(75, 75));
        a44.setPreferredSize(new java.awt.Dimension(75, 75));
        a44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a45.setMaximumSize(new java.awt.Dimension(75, 75));
        a45.setMinimumSize(new java.awt.Dimension(75, 75));
        a45.setName(""); // NOI18N
        a45.setPreferredSize(new java.awt.Dimension(75, 75));
        a45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a46.setMaximumSize(new java.awt.Dimension(75, 75));
        a46.setMinimumSize(new java.awt.Dimension(75, 75));
        a46.setName(""); // NOI18N
        a46.setPreferredSize(new java.awt.Dimension(75, 75));
        a46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a47.setMaximumSize(new java.awt.Dimension(75, 75));
        a47.setMinimumSize(new java.awt.Dimension(75, 75));
        a47.setName(""); // NOI18N
        a47.setPreferredSize(new java.awt.Dimension(75, 75));
        a47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a48.setMaximumSize(new java.awt.Dimension(75, 75));
        a48.setMinimumSize(new java.awt.Dimension(75, 75));
        a48.setName(""); // NOI18N
        a48.setPreferredSize(new java.awt.Dimension(75, 75));
        a48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a49.setMaximumSize(new java.awt.Dimension(75, 75));
        a49.setMinimumSize(new java.awt.Dimension(75, 75));
        a49.setName(""); // NOI18N
        a49.setPreferredSize(new java.awt.Dimension(75, 75));
        a49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a50.setMaximumSize(new java.awt.Dimension(75, 75));
        a50.setMinimumSize(new java.awt.Dimension(75, 75));
        a50.setName(""); // NOI18N
        a50.setPreferredSize(new java.awt.Dimension(75, 75));
        a50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a51.setMaximumSize(new java.awt.Dimension(75, 75));
        a51.setMinimumSize(new java.awt.Dimension(75, 75));
        a51.setName(""); // NOI18N
        a51.setPreferredSize(new java.awt.Dimension(75, 75));
        a51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a52.setMaximumSize(new java.awt.Dimension(75, 75));
        a52.setMinimumSize(new java.awt.Dimension(75, 75));
        a52.setName(""); // NOI18N
        a52.setPreferredSize(new java.awt.Dimension(75, 75));
        a52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a53.setMaximumSize(new java.awt.Dimension(75, 75));
        a53.setMinimumSize(new java.awt.Dimension(75, 75));
        a53.setPreferredSize(new java.awt.Dimension(75, 75));
        a53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a54.setMaximumSize(new java.awt.Dimension(75, 75));
        a54.setMinimumSize(new java.awt.Dimension(75, 75));
        a54.setPreferredSize(new java.awt.Dimension(75, 75));
        a54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a55.setMaximumSize(new java.awt.Dimension(75, 75));
        a55.setMinimumSize(new java.awt.Dimension(75, 75));
        a55.setName(""); // NOI18N
        a55.setPreferredSize(new java.awt.Dimension(75, 75));
        a55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a56.setMaximumSize(new java.awt.Dimension(75, 75));
        a56.setMinimumSize(new java.awt.Dimension(75, 75));
        a56.setName(""); // NOI18N
        a56.setPreferredSize(new java.awt.Dimension(75, 75));
        a56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a57.setMaximumSize(new java.awt.Dimension(75, 75));
        a57.setMinimumSize(new java.awt.Dimension(75, 75));
        a57.setName(""); // NOI18N
        a57.setPreferredSize(new java.awt.Dimension(75, 75));
        a57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a58.setMaximumSize(new java.awt.Dimension(75, 75));
        a58.setMinimumSize(new java.awt.Dimension(75, 75));
        a58.setName(""); // NOI18N
        a58.setPreferredSize(new java.awt.Dimension(75, 75));
        a58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a59.setMaximumSize(new java.awt.Dimension(75, 75));
        a59.setMinimumSize(new java.awt.Dimension(75, 75));
        a59.setName(""); // NOI18N
        a59.setPreferredSize(new java.awt.Dimension(75, 75));
        a59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a60.setMaximumSize(new java.awt.Dimension(75, 75));
        a60.setMinimumSize(new java.awt.Dimension(75, 75));
        a60.setPreferredSize(new java.awt.Dimension(75, 75));
        a60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a61.setMaximumSize(new java.awt.Dimension(75, 75));
        a61.setMinimumSize(new java.awt.Dimension(75, 75));
        a61.setName(""); // NOI18N
        a61.setPreferredSize(new java.awt.Dimension(75, 75));
        a61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a62.setMaximumSize(new java.awt.Dimension(75, 75));
        a62.setMinimumSize(new java.awt.Dimension(75, 75));
        a62.setName(""); // NOI18N
        a62.setPreferredSize(new java.awt.Dimension(75, 75));
        a62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        a63.setMaximumSize(new java.awt.Dimension(75, 75));
        a63.setMinimumSize(new java.awt.Dimension(75, 75));
        a63.setPreferredSize(new java.awt.Dimension(75, 75));
        a63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClick(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        jButton1.setText("New Game?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(a37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(a39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(a36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(a25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(a18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(a9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a00, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a23, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a20, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a19, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a18, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a31, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a24, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a28, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a26, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a25, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a30, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a29, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a27, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a33, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a36, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a34, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a35, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a37, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a38, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a32, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a39, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a45, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(a40, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a44, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a42, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a43, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a47, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a46, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a41, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a59, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a62, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a60, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a61, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a63, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a48, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a58, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a49, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a55, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a50, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a54, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a52, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a53, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a57, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a56, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a51, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        a00.getAccessibleContext().setAccessibleName("01");
        a1.getAccessibleContext().setAccessibleName("00");
        a2.getAccessibleContext().setAccessibleName("07");
        a3.getAccessibleContext().setAccessibleName("02");
        a4.getAccessibleContext().setAccessibleName("04");
        a5.getAccessibleContext().setAccessibleName("03");
        a6.getAccessibleContext().setAccessibleName("05");
        a7.getAccessibleContext().setAccessibleName("06");
        a8.getAccessibleContext().setAccessibleName("11");
        a9.getAccessibleContext().setAccessibleName("10");
        a10.getAccessibleContext().setAccessibleName("17");
        a11.getAccessibleContext().setAccessibleName("12");
        a12.getAccessibleContext().setAccessibleName("14");
        a13.getAccessibleContext().setAccessibleName("13");
        a14.getAccessibleContext().setAccessibleName("15");
        a15.getAccessibleContext().setAccessibleName("17");
        a16.getAccessibleContext().setAccessibleName("23");
        a17.getAccessibleContext().setAccessibleName("26");
        a18.getAccessibleContext().setAccessibleName("20");
        a19.getAccessibleContext().setAccessibleName("22");
        a20.getAccessibleContext().setAccessibleName("21");
        a21.getAccessibleContext().setAccessibleName("25");
        a22.getAccessibleContext().setAccessibleName("24");
        a23.getAccessibleContext().setAccessibleName("27");
        a24.getAccessibleContext().setAccessibleName("37");
        a25.getAccessibleContext().setAccessibleName("30");
        a26.getAccessibleContext().setAccessibleName("32");
        a27.getAccessibleContext().setAccessibleName("33");
        a28.getAccessibleContext().setAccessibleName("31");
        a29.getAccessibleContext().setAccessibleName("35");
        a30.getAccessibleContext().setAccessibleName("34");
        a31.getAccessibleContext().setAccessibleName("36");
        a32.getAccessibleContext().setAccessibleName("45");
        a33.getAccessibleContext().setAccessibleName("46");
        a34.getAccessibleContext().setAccessibleName("41");
        a35.getAccessibleContext().setAccessibleName("42");
        a36.getAccessibleContext().setAccessibleName("47");
        a37.getAccessibleContext().setAccessibleName("40");
        a38.getAccessibleContext().setAccessibleName("44");
        a39.getAccessibleContext().setAccessibleName("43");
        a40.getAccessibleContext().setAccessibleName("57");
        a41.getAccessibleContext().setAccessibleName("53");
        a42.getAccessibleContext().setAccessibleName("52");
        a43.getAccessibleContext().setAccessibleName("50");
        a44.getAccessibleContext().setAccessibleName("51");
        a45.getAccessibleContext().setAccessibleName("56");
        a46.getAccessibleContext().setAccessibleName("55");
        a47.getAccessibleContext().setAccessibleName("54");
        a48.getAccessibleContext().setAccessibleName("64");
        a49.getAccessibleContext().setAccessibleName("63");
        a50.getAccessibleContext().setAccessibleName("77");
        a51.getAccessibleContext().setAccessibleName("73");
        a52.getAccessibleContext().setAccessibleName("72");
        a53.getAccessibleContext().setAccessibleName("70");
        a53.getAccessibleContext().setAccessibleDescription("7");
        a54.getAccessibleContext().setAccessibleName("71");
        a55.getAccessibleContext().setAccessibleName("76");
        a56.getAccessibleContext().setAccessibleName("75");
        a57.getAccessibleContext().setAccessibleName("74");
        a58.getAccessibleContext().setAccessibleName("65");
        a59.getAccessibleContext().setAccessibleName("66");
        a60.getAccessibleContext().setAccessibleName("61");
        a61.getAccessibleContext().setAccessibleName("62");
        a62.getAccessibleContext().setAccessibleName("67");
        a63.getAccessibleContext().setAccessibleName("60");
        jButton1.getAccessibleContext().setAccessibleDescription("restart");

        getAccessibleContext().setAccessibleName("15");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JButton button = (JButton)evt.getSource();
    String a = button.getAccessibleContext().getAccessibleName();
    this.mvcMessaging.notify("newGame", a);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void onClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClick
    JButton button = (JButton)evt.getSource();
    String a = button.getAccessibleContext().getAccessibleName();
    this.mvcMessaging.notify("playerMove", a);
    }//GEN-LAST:event_onClick

    
    private int checkRed(Object Board) {
         String[][] board = (String[][])Board;
         int red = 0;
         for (int i = 0; i < 8; i++) {
             for (int f = 0; f < 8; f++) {
                 if ("red".equals(board[i][f])) {
                     red++;
                 }
             }
         }
         return red;
    }
    private int checkBlue(Object Board) {
         String[][] board = (String[][])Board;
         int blue = 0;
         for (int i = 0; i < 8; i++) {
             for (int f = 0; f < 8; f++) {
                 if ("blue".equals(board[i][f])) {
                     blue++;
                 }
             }
         }
         return blue;
    }
  /**Controller.java:78
   * @param args the command line arguments
   */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a00;
    private javax.swing.JButton a1;
    private javax.swing.JButton a10;
    private javax.swing.JButton a11;
    private javax.swing.JButton a12;
    private javax.swing.JButton a13;
    private javax.swing.JButton a14;
    private javax.swing.JButton a15;
    private javax.swing.JButton a16;
    private javax.swing.JButton a17;
    private javax.swing.JButton a18;
    private javax.swing.JButton a19;
    private javax.swing.JButton a2;
    private javax.swing.JButton a20;
    private javax.swing.JButton a21;
    private javax.swing.JButton a22;
    private javax.swing.JButton a23;
    private javax.swing.JButton a24;
    private javax.swing.JButton a25;
    private javax.swing.JButton a26;
    private javax.swing.JButton a27;
    private javax.swing.JButton a28;
    private javax.swing.JButton a29;
    private javax.swing.JButton a3;
    private javax.swing.JButton a30;
    private javax.swing.JButton a31;
    private javax.swing.JButton a32;
    private javax.swing.JButton a33;
    private javax.swing.JButton a34;
    private javax.swing.JButton a35;
    private javax.swing.JButton a36;
    private javax.swing.JButton a37;
    private javax.swing.JButton a38;
    private javax.swing.JButton a39;
    private javax.swing.JButton a4;
    private javax.swing.JButton a40;
    private javax.swing.JButton a41;
    private javax.swing.JButton a42;
    private javax.swing.JButton a43;
    private javax.swing.JButton a44;
    private javax.swing.JButton a45;
    private javax.swing.JButton a46;
    private javax.swing.JButton a47;
    private javax.swing.JButton a48;
    private javax.swing.JButton a49;
    private javax.swing.JButton a5;
    private javax.swing.JButton a50;
    private javax.swing.JButton a51;
    private javax.swing.JButton a52;
    private javax.swing.JButton a53;
    private javax.swing.JButton a54;
    private javax.swing.JButton a55;
    private javax.swing.JButton a56;
    private javax.swing.JButton a57;
    private javax.swing.JButton a58;
    private javax.swing.JButton a59;
    private javax.swing.JButton a6;
    private javax.swing.JButton a60;
    private javax.swing.JButton a61;
    private javax.swing.JButton a62;
    private javax.swing.JButton a63;
    private javax.swing.JButton a7;
    private javax.swing.JButton a8;
    private javax.swing.JButton a9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
